language: node_js

node_js:
  - "10"
  - "8"

script:
  - npm run lint
  - npm run build
  - "npm run test:es5"
  - npm run test
  - "npm run test:perf"

after_success:
  - codecov

cache:
  directories:
    - "$HOME/.npm"
